title: Adam's Life Blog
author: MayerAdam
email: adamthemayer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn about Adam's life, interests, and professional experiences in this
  interactive blog post!
theme: minima

# social links
github_username:  MayerAdam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
  - jemoji
